[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.4.0"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[prune]
  go-tests = true
  unused-packages = true
